### PR TITLE
some changes

### PR DESCRIPTION
**Pull request by SagenHansda19**
i added the feature of background image for each weather

### CODE REVIEW

**Review by abdullah4tech — COMMENTED** [review]
Thanks for contributing @SagenHansda19 🫡

**Comment by SagenHansda19** [comment]
Always happy to contribute and learn

**Comment by abdullah4tech** [comment]
I will like to connect with you man

**Comment by SagenHansda19** [comment]
sure, this is my linkedin [Sagen Hansda](www.linkedin.com/in/sagen-hansda)

**Pull request merged**
